### ISSUE TITLE
BM25 from treesitter function calls

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgsimil#14]
Use code from https://github.com/ropensci-review-tools/pkgstats/pull/62#issuecomment-2359834446 to get all function call tags from tree-sitter, and then use all of those in a separate BM25 analysis

---

## TODO

- [x] Add tests
- [x] Upload [binary data](https://github.com/ropensci-review-tools/pkgsimil/releases/tag/v0.1.2)
- [x] Use those data to calculate separate BM25 measure
- [x] Incorporate this code-based BM25 with embedding similarities to generate final similarity metric for code

**Comment by mpadge** [comment]
Re-opening to add tests

**Comment by mpadge** [comment]
Re-opening to remove all Recommended pkgs from DESC file, and to use `asNamespace()` to get function names, and not `requireNamespace()`. The former just reads the namespace file from .libPaths without loading at all.
